### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by keyplay** [tilman151/rul-datasets#43]
There is an error when running examples code in https://krokotsch.eu/rul-datasets/api/rul_datasets/baseline/.
Error msg is " AttributeError: 'RulDataModule' object has no attribute '_data' " when executing  baseline_dm.train_dataloader().

I guess baseline_dm.prepare_data(); baseline_dm.setup() should be executed first.

**Comment by tilman151** [comment]
Thanks for debugging my examples for me 😄 

I'll fix it this week.
